"""Phase exit tests for FindandSeek."""

from __future__ import annotations

import sqlite3
import tempfile
import time
from pathlib import Path

import pytest

from find_and_seek.db.connection import init_db
from find_and_seek.db.store import (
    enqueue,
    file_with_hash,
    get_stored_hash,
    mark_done,
    purge_file_by_path,
    sha256_file,
    update_path,
)
from find_and_seek.ingest.chunk import chunk_blocks, estimate_tokens
from find_and_seek.ingest.extract.router import ExtractError, extract_file
from find_and_seek.ingest.worker import index_file, process_batch
from find_and_seek.search.hybrid import search

CORPUS = Path(__file__).parent / "corpus"


# The corpus is generated by conftest at import time (it is gitignored — see the
# comment there), so it exists before this module is collected.


@pytest.fixture
def test_db(monkeypatch):
    monkeypatch.setenv("FINDANDSEEK_TEST", "1")
    with tempfile.TemporaryDirectory() as tmp:
        db_path = Path(tmp) / "test.db"
        conn = init_db(db_path)
        yield conn
        conn.close()


# ── Phase 1 ──────────────────────────────────────────────────────


class TestPhase1:
    def test_all_fixtures_have_blocks(self):
        skip = {"corrupt.pdf"}
        for path in CORPUS.iterdir():
            if path.suffix == ".pdf" and path.name in skip:
                continue
            if path.name.startswith("."):
                continue
            result = extract_file(path)
            if path.name == "empty.docx":
                assert len(result.blocks) == 0 or result.blocks[0].text == ""
                continue
            if path.name in ("photo_with_sign.jpg", "board_deck.pptx", "scanned_letter.pdf"):
                assert len(result.images) >= 1 or len(result.blocks) >= 1
                continue
            assert len(result.blocks) >= 1, path.name
            chunks = chunk_blocks(result.blocks, path_hint=path.name)
            assert all(c.location_ref for c in chunks), path.name

    def test_every_watched_format_has_an_extractor(self):
        # Regression guard: a format that's watched but has no extractor ingests to
        # an empty record — the engine goes blind to it (real bug: .rtf/.odt/.doc
        # were watched with no handler). Keep the two sets in lockstep.
        from find_and_seek.ingest.extract.router import EXTRACTORS, WATCHED_EXTENSIONS

        missing = WATCHED_EXTENSIONS - set(EXTRACTORS)
        assert not missing, f"watched formats with no extractor: {sorted(missing)}"

    def test_corrupt_pdf_handled(self):
        with pytest.raises(ExtractError):
            extract_file(CORPUS / "corrupt.pdf")

    def test_contract_long_chunks(self):
        result = extract_file(CORPUS / "contract_long.pdf")
        chunks = chunk_blocks(result.blocks, path_hint="contract_long.pdf")
        assert len(chunks) >= 10
        assert max(c.token_estimate for c in chunks) >= 300

    def test_xlsx_sheet_summaries(self):
        result = extract_file(CORPUS / "cashflow.xlsx")
        assert all("Sheet" in b.text for b in result.blocks)
        assert all(b.source_type == "table" for b in result.blocks)


# ── Phase 2 ──────────────────────────────────────────────────────


class TestPhase2:
    def _index_corpus(self, conn: sqlite3.Connection) -> None:
        for path in sorted(CORPUS.iterdir()):
            if path.name.startswith("."):
                continue
            enqueue(conn, str(path.resolve()), "created")
            conn.commit()
        while True:
            n = process_batch(conn)
            if n == 0:
                pending = conn.execute(
                    "SELECT COUNT(*) FROM ingest_queue WHERE status='pending'"
                ).fetchone()[0]
                if pending == 0:
                    break

    def test_index_and_search(self, test_db):
        self._index_corpus(test_db)
        indexed = test_db.execute("SELECT COUNT(*) FROM files WHERE status='indexed'").fetchone()[0]
        failed = test_db.execute("SELECT COUNT(*) FROM files WHERE status='failed'").fetchone()[0]
        assert indexed >= 13
        assert failed >= 1

        hits, ms = search(test_db, "plumber invoice from March", limit=5)
        filenames = [h.filename for h in hits]
        assert "invoice_plumber_march.pdf" in filenames[:3]

        hits2, ms2 = search(test_db, "letter to the council park renovation", limit=5)
        assert hits2[0].filename == "letter_to_council.docx"
        assert ms < 2000  # generous for CI without ONNX

    def test_duplicate_hash(self, test_db):
        self._index_corpus(test_db)
        h1 = test_db.execute(
            "SELECT content_hash FROM files WHERE filename='invoice_plumber_march.pdf'"
        ).fetchone()[0]
        h2 = test_db.execute(
            "SELECT content_hash FROM files WHERE filename='duplicate_of_1.pdf'"
        ).fetchone()[0]
        assert h1 == h2


# ── Phase 3 ──────────────────────────────────────────────────────


class TestPhase3:
    def test_hash_guard_no_reingest(self, test_db):
        path = CORPUS / "notes.txt"
        index_file(test_db, str(path.resolve()))
        chunks_before = test_db.execute("SELECT COUNT(*) FROM file_chunks").fetchone()[0]
        h = sha256_file(path)
        assert get_stored_hash(test_db, str(path.resolve())) == h
        enqueue(test_db, str(path.resolve()), "modified")
        test_db.commit()
        process_batch(test_db)
        chunks_after = test_db.execute("SELECT COUNT(*) FROM file_chunks").fetchone()[0]
        assert chunks_before == chunks_after

    def test_rename_updates_path(self, test_db):
        import shutil

        src = CORPUS / "notes.md"
        index_file(test_db, str(src.resolve()))
        row = test_db.execute("SELECT id, content_hash FROM files WHERE path=?", (str(src.resolve()),)).fetchone()
        fid, h = row[0], row[1]
        with tempfile.TemporaryDirectory() as tmp:
            dest = Path(tmp) / "renamed_notes.md"
            shutil.copy(src, dest)
            update_path(test_db, fid, str(dest))
            test_db.commit()
            count = test_db.execute("SELECT COUNT(*) FROM file_chunks WHERE file_id=?", (fid,)).fetchone()[0]
            assert count > 0

    def test_delete_cascades(self, test_db):
        path = CORPUS / "data.json"
        index_file(test_db, str(path.resolve()))
        fid = test_db.execute("SELECT id FROM files WHERE path=?", (str(path.resolve()),)).fetchone()[0]
        purge_file_by_path(test_db, str(path.resolve()))
        test_db.commit()
        assert test_db.execute("SELECT COUNT(*) FROM files WHERE id=?", (fid,)).fetchone()[0] == 0
        assert test_db.execute("SELECT COUNT(*) FROM file_chunks WHERE file_id=?", (fid,)).fetchone()[0] == 0


# ── Phase 5 ──────────────────────────────────────────────────────


class TestPhase5:
    def test_summary_and_entity(self, test_db):
        for name in ("invoice_plumber_march.pdf", "letter_to_council.docx"):
            index_file(test_db, str((CORPUS / name).resolve()))
        inv = test_db.execute(
            """
            SELECT fs.document_type, fs.key_facts, f.id
            FROM file_summaries fs JOIN files f ON f.id=fs.file_id
            WHERE f.filename='invoice_plumber_march.pdf'
            """
        ).fetchone()
        assert inv is not None
        assert inv[0] in ("invoice", "other")

        # person/org entities come solely from extract_kf_entities (LLM key_facts) — not spaCy.
        # Verify the path works with a synthetic summary:
        from find_and_seek.ingest.ner import extract_kf_entities
        ents = extract_kf_entities({
            "key_facts": {"employee": "Clancy Morrison"},
            "one_line_anchor": "",
        })
        assert any(e["entity_type"] == "person" and "clancy" in e["entity_value"] for e in ents)
